name: art_gallery

description: "Art gallery app."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  auto_route: ^9.2.2
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  dio: ^5.7.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  rxdart: ^0.28.0
  equatable: ^2.0.7
  cached_network_image: ^3.4.1
  flutter_html: ^3.0.0-beta.2
  url_launcher: ^6.3.1
  photo_view: ^0.15.0

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.0


flutter:
  uses-material-design: true

  assets:
    - assets/
